create extension if not exists pgcrypto;

create table if not exists public.reports (
  id uuid primary key,
  target_origin text not null,
  target_url_redacted text not null,
  grade text not null check (grade in ('A', 'B', 'C', 'D', 'F')),
  score integer not null check (score >= 0 and score <= 100),
  scanner jsonb not null,
  findings jsonb not null default '[]'::jsonb,
  aggregate jsonb not null default '{}'::jsonb,
  authorization_artifact jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  name text not null check (
    name in (
      'scan_started',
      'scan_completed',
      'report_viewed',
      'share_clicked',
      'waitlist_submitted',
      'stripe_clicked'
    )
  ),
  report_id uuid references public.reports(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.waitlist_entries (
  id bigint generated by default as identity primary key,
  email text not null,
  email_hash text not null,
  report_id uuid references public.reports(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.rate_limit_events (
  id bigint generated by default as identity primary key,
  scope text not null check (
    scope in (
      'requester_hour',
      'requester_day',
      'origin_hour'
    )
  ),
  key text not null,
  created_at timestamptz not null default now()
);

alter table public.waitlist_entries add column if not exists email text;

create index if not exists reports_created_at_idx on public.reports(created_at desc);
create index if not exists events_created_at_idx on public.events(created_at desc);
create index if not exists events_report_id_idx on public.events(report_id);
create index if not exists waitlist_entries_created_at_idx on public.waitlist_entries(created_at desc);
create index if not exists waitlist_entries_email_hash_idx on public.waitlist_entries(email_hash);
create index if not exists rate_limit_events_lookup_idx on public.rate_limit_events(scope, key, created_at desc);

alter table public.reports enable row level security;
alter table public.events enable row level security;
alter table public.waitlist_entries enable row level security;
alter table public.rate_limit_events enable row level security;

grant usage on schema public to service_role;
grant select, insert, update, delete on public.reports to service_role;
grant select, insert, update, delete on public.events to service_role;
grant select, insert, update, delete on public.waitlist_entries to service_role;
grant select, insert, update, delete on public.rate_limit_events to service_role;
grant usage, select on all sequences in schema public to service_role;

comment on table public.reports is
  'VibeCheck report metadata and redacted findings only. Never store raw secrets, source maps, source code, DB rows, cookies, auth headers, or target response bodies.';
comment on column public.reports.authorization_artifact is
  'Supabase gated-check authorization artifact: scan ID, target origin, timestamp, checkbox text version, and privacy-safe requester fingerprint.';
comment on table public.rate_limit_events is
  'Server-side scan rate limit events. Required in production so Vercel/serverless instances fail closed instead of relying on memory.';
